server:
    port: 10010
    servlet:
        context-path: /articlemodule
spring:
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

