server:
    port: 8092
    servlet:
        context-path: /user


spring:
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

    #redis连接配置
    redis:
        database: 8
        host: 106.12.55.131
        port: 6379
        password:
        app: base
    data:
        redis:
          repositories:
            enabled: false




