spring:
    #redis连接配置
    redis:
      database: 15
      host: 106.12.55.131
      port: 6379
      password:
      app: ph
    data:
        redis:
          repositories:
            enabled: false
spring.application.name=eureka-service
# 修改端口
server.port=1000

# 实例的主机名称
eureka.instance.hostname=127.0.0.1

## 不要向注册中心注册自己
eureka.client.register-with-eureka=false
## 表示不去检索其他的服务，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
eureka.client.fetch-registry=false

# 指定服务注册中心地址 这里直接指向了本服务
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/